# --- Site ---
title: "Laboratoires de Sécurité des Réseaux"
description: "Cours IPTables / Réseaux"
url: "https://celinepieczuk.github.io"   # ton domaine
baseurl: ""                               # vide si repo utilisateur (celinepieczuk.github.io)

# --- Thème ---
# enlève: theme: jekyll-theme-minimal
remote_theme: kevinlin1/just-the-class

# --- Plugins (GH Pages supporte celui-ci) ---
plugins:
  - jekyll-remote-theme

# --- Nav (optionnel, exemple de menu haut) ---
just_the_class:
  collections:
    # active les annonces si tu en veux (facultatif)
    announcements:
      output: true
  footer_content: ""   # masque le footer par défaut si tu veux

# --- Collections par défaut (facultatif) ---
collections:
  announcements:
    output: true

# --- Options Markdown (conserve ce que tu avais) ---
markdown: kramdown
highlighter: rouge
